### ISSUE TITLE
Missing dimension text and text style

### ISSUE THREAD

**Issue by rola22** [LibreCAD/LibreCAD#1489] opened 2022-01-03 19:26 UTC
Hello.

Today i downloaded and compiled latest version of LibreCAD.
What i found is that i cannot see dimension text. I opened Options -> Current Drawing Preferences -> Dimensions
and i didn't found Text style for dimension, drop-down list is empty.

I'm using Linux Mint 20.2 Cinnamon with 5.11.0-43-generic  #kernel

![bitmapa](https://user-images.githubusercontent.com/25638101/147971173-559c053d-038d-4363-9310-223ff692a180.png)

**Comment by rola22** [comment] 2022-01-03 19:49
And looks like i found issue - it was me.
I've compiled Librecad on my secondary drive, which is in home/.../media/...

When i compiled it again on my main drive everything is ok.

But what i want to use my second drive for compiled programs? How to compile them correctly?

**Comment by fa201** [comment] 2022-01-03 19:52
I can compile on secondary drive hosting my home directory on Ubuntu.
Did you try this proceedure: https://librecad.readthedocs.io/en/latest/appx/build.html?highlight=compile#building-on-linux

**Comment by rola22** [comment] 2022-01-03 22:05
Yes, i was following this guide but instead of downloading zip file i cloned source code.

**Comment by lordofbikes** [comment] 2022-01-03 22:48
This is possibly related with #1488

**Comment by lordofbikes** [comment] 2022-01-04 20:42
I checked this, it is indeed a duplicate of #1488, please follow there

**Closed by lordofbikes** 2022-01-04 20:42 UTC
Labels: duplicate
