### ISSUE TITLE
Dock widgets expand when switching to Print Preview

### ISSUE THREAD

**Issue by dellus** [LibreCAD/LibreCAD#1857] opened 2024-08-26 12:53 UTC
Expected behavior: Dock widgets should stay as set in drawing mode when switching to Print Preview

 Observed behavior: Dock widgets expand when switching to Print Preview and stays so when returning to drawing mode. Same issue as previous issue #1752

Version: 2.2.2_alpha1-143-g466d081d
Compiler: GNU GCC 9.4.0
Compiled on: Aug 25 2024
Qt Version: 6.6.3
Boost Version: 1.71.0
System: fossapup64 9.5
Linux appimage

**Comment by app4soft** [comment] 2024-08-26 13:38
It is duplicate of https://github.com/LibreCAD/LibreCAD/issues/1848

You may close this issue.

**Closed** 2024-08-26 13:53 UTC
