### ISSUE TITLE
Need to enable the use of TTF Fonts directly into LibreCAD

### ISSUE THREAD

**Issue by ajk2196** [LibreCAD/LibreCAD#1523] opened 2022-02-24 10:56 UTC
We need to implement the direct usage of TTF fonts into LibreCAD. The reason behind this request is that the LFF Fonts are hollow; only the outlines act out into drawings. However, It would be much more helpful if the fonts were solid filled. As of now, producing such fonts is not possible using the TTF2LFF converter. Therefore, implementing this feature would enable proper highlighting. 'Highlighting', because the existing fonts' outlines are so thin that on a black and white plan print, it is easy to overlook a worded detail. However, if these fonts are solid filled, then it will give a good shape to the document and its details.

**Comment by lordofbikes** [comment] 2022-02-24 12:28
duplicate of #1105

**Closed by lordofbikes** 2022-02-24 12:28 UTC
Labels: feature request, duplicate
