### ISSUE TITLE
Print Preview Problem

### ISSUE THREAD

**Issue by Quinkink** [LibreCAD/LibreCAD#1332] opened 2021-03-26 00:23 UTC
### Expected behavior
Using Print Preview to scale and center project on page
When leaving Print Preview I expected the config to be saved and ready for printing.

### Observed behavior
Once the Print preview in Un-Toggled
- current project is closed
- an empty project is opened

### Steps to reproduce or sample file
Project finished and saved
Open Print preview window
Select custom scale + press return
Press button to center project on paper
Leave Print preview (File>Un-Toggle Print preview)

### Operating System and LibreCAD version info
Windows 10
LibreCAD : LibreCAD-Installer-2.2.0-rc2-8-g8b2b62d1

**Comment by lordofbikes** [comment] 2021-03-26 07:47
This is a duplicate of #944 and #1207.
An explanation is in my response in #1207.
#1207 is about Tab mode, but it applies to Window mode too.
Basically print preview is just another tab/window and when you close it, another tab/window has to be activated again.
LibreCAD is missing a logic which tab/window was active before print preview was opened, so it defaults to the first, which is the empty drawing opened on start usually.
You can try tab mode or not to maximize the drawing window to see that the drawing project is still open.
Or look in the Drawings menu, where the open tabs/windows are listed.

I'll close this as it is linked with #1207 now.

**Closed by lordofbikes** 2021-03-26 07:47 UTC
