### ISSUE TITLE
command language chages only with interface

### ISSUE THREAD

**Issue by Hoksmur** [LibreCAD/LibreCAD#1356] opened 2021-06-08 09:08 UTC
### Expected behavior
When intarface is russian and command enlish, I should use **line** but not **линия**.

### Observed behavior
I can use only **линия** (not **line**) with interface *russian* and command language *english*.

### Steps to reproduce or sample file
 Apply settings and try do it.

### Operating System and LibreCAD version info
Version: 2.2.0-rc2-19-ge02f3580
Compiler: GNU GCC 7.3.0
Build: May 16 2021
Ver Qt: 5.12.4
Ver Boost: 1.65.1
Система: Windows 10 (10.0)

**Comment by lordofbikes** [comment] 2023-03-10 13:12
duplicate of #976

**Closed by lordofbikes** 2023-03-10 13:12 UTC
