### ISSUE TITLE
Nonsense error message after cancelling open DWG file

### ISSUE THREAD

**Issue by teo1978** [LibreCAD/LibreCAD#1163] opened 2019-11-25 13:11 UTC
### Steps to reproduce or sample file

1. Go to **File -> Open**
2. Select a **.dwg** file
3. A confirmation prompt shows up, alerting that this is experimental and to save your work first (it should emphasize more that it might actually stall the whole system, btw)
4. So click on **Cancel**

### Expected behavior

Nothing, should just cancel opening the file, close the popup and do nothing.

### Observed behavior

A nonsense error message shows up in a new popup window that says:

```Cannot open the file
/path/to/file.dwg
Please check its existence and permissions.
```

### Operating System and LibreCAD version info

```
Version: master
SCM Revision: 2.0.9
Compiler: GNU GCC 5.3.1
Qt Version: 5.5.1
Compiled on: Mar 24 2016
```

On unbuntu 16.04 from https://launchpad.net/~librecad-dev/+archive/ubuntu/librecad-stable

**Comment by lordofbikes** [comment] 2022-05-29 08:48
Even when the steps are different, this issue is a duplicate of #1164.
As the title implies that this issue is DWG related, which is not the case, I close this one.
It is now linked to #1164.

**Closed by lordofbikes** 2022-05-29 08:48 UTC
Labels: reproducible, inquiry, duplicate, restriction
