### ISSUE TITLE
Fix the Status Bar size readjusting everytime when saving.

### ISSUE THREAD

**Issue by ajk2196** [LibreCAD/LibreCAD#1470] opened 2021-12-19 17:05 UTC
This is really an annoying thing. The status bar resizes everytime I save my drawing. This resizing moves the entire drawing space up and down and happens just before I have snapped a point and about to click. Many a times, I click on a different snap point and this causes me to go back and redo it. It may seem a simple thing, but when you multiply this by about a hundred times for a single day for six working days a week, it becomes really annoying. Kindly please fix this.

Windows 10.
Version: 2.2.0-rc3
Compiler: GNU GCC 7.3.0
Compiled on: Nov 29 2021
Qt Version: 5.12.4
Boost Version: 1.65.1

**Comment by lordofbikes** [comment] 2021-12-19 19:42
duplicate of #1026

**Closed by lordofbikes** 2021-12-19 19:42 UTC
Labels: duplicate
