### ISSUE TITLE
Layer of selected elements changed when clicking on another layer on Linux

### ISSUE THREAD

**Issue by Rupicapra-rupicapra** [LibreCAD/LibreCAD#556] opened 2015-08-28 12:29 UTC
Concerned platforms & versions :
 - Linux Mint 17.2 64 bits with LC V2.0.(2/4?)
 - Linux Mint 17.2 64 bits with LC nightly build
 - Debian GNU/Linux 8 Jessie 64 bits with LC V2.0.4-1

How to reproduce :
 - Create a new drawing or open an existing one.
 - If there is only layer 0, create another layer.
 - If no entity, draw an entity.
 - Select an entity.
 - In layers list, click on another layer name.
 - The entity is now in that other layer.

**Comment by lordofbikes** [comment] 2015-08-28 12:50
Duplicate of #533, please find the answer there.

**Closed by lordofbikes** 2015-08-28 12:50 UTC
