### ISSUE TITLE
Command Language English but some commands are Turkish

### ISSUE THREAD

**Issue by akcansoft** [LibreCAD/LibreCAD#1597] opened 2023-03-10 12:44 UTC
### Expected behavior
In the program preferences, the command language is set to "English" and the GUI language is set to "Turkish(Türkçe)".
But some commands are Turkish. For example: açı, başl, dikdörtgen, çember, çizgi ... etc.
All commands are expected to be in English.

### Operating System and LibreCAD version info
OS: Windows 11
LibreCAD v 2.2.0-2-gf55f341e
Compiler: GNU GCC 12.2.0
Compiled on: Dec 19 2022
Qt Version: 5.12.11
Boost Version: 1.75.0
![turkish-commands](https://user-images.githubusercontent.com/7031346/224318550-7e205ed3-eb18-4964-bd0b-2bcd22c39097.jpg)

**Comment by lordofbikes** [comment] 2023-03-10 13:13
duplicate of #976, #1356

**Closed by lordofbikes** 2023-03-10 13:13 UTC
