### ISSUE TITLE
Status bar height toggling

### ISSUE THREAD

**Issue by gwilku** [LibreCAD/LibreCAD#1346] opened 2021-05-05 17:50 UTC
### Expected behavior

I would expect the status bar (with tooltips, coordinates, etc.) to be of a fixed height.

### Observed behavior

Status bar changes it's height depending on the contents: it's one-text-line high after saving or auto-saving, while it's twice as high when any tool is selected.

### Steps to reproduce or sample file

Start LibreCAD, select any tool, make a change (draw, move, whatever) to the dcoument, wait for auto-save OR - on a previously saved file: hit Ctrl+S

### Operating System and LibreCAD version info

Version: 2.2.0-rc2-15-g76828565
Compiler: GNU GCC 7.3.0
Compiled on: Apr 13 2021
Qt Version: 5.12.4
Boost Version: 1.65.1
System: Windows 10 (10.0)

**Comment by lordofbikes** [comment] 2021-05-05 19:24
duplicate of #1026

**Closed by lordofbikes** 2021-05-05 19:24 UTC
Labels: duplicate, restriction
