### ISSUE TITLE
Circle and Ellipse has issues with different line types

### ISSUE THREAD

**Issue by app4soft** [LibreCAD/LibreCAD#1657] opened 2023-07-14 17:55 UTC
### Expected behavior

All entities with the same line type should be drown as expected. 

### Observed behavior

Actually there are issue with line types applied, especially applied to Circle and Ellipse,:

1. Circles has different dash/dot/space sizes (smaller) then all other entities;
2. Ellipses has a bit broken look with all line types;
3. Splines with "No Pen" shown as "Continuous";
4. "Dash Dot" and "Dash Dot (small)" has a bit off-centered middle dots (an all objects, except Circle).

**Here is testcase DXF**: [line-types.zip](https://github.com/LibreCAD/LibreCAD/files/12136821/line-types.zip) (updated on 2023/07/22)

![screen-2023-07-14-21-48-11](https://github.com/LibreCAD/LibreCAD/assets/22447924/a510aa5d-0cdf-43b2-b2a6-e7a4a1a5f4a1)
![screen-2023-07-14-20-26-31](https://github.com/LibreCAD/LibreCAD/assets/22447924/3c84ded5-3b18-4dc1-bd7d-e8c00afbf601)
![screen-2023-07-14-20-26-08](https://github.com/LibreCAD/LibreCAD/assets/22447924/9e4d96d6-9881-49ab-a6b4-bab298e433ca)
![screen-2023-07-14-22-28-36](https://github.com/LibreCAD/LibreCAD/assets/22447924/cde25ef0-5b7b-456f-944a-33fdbebb3967)
![screen-2023-07-14-20-25-46](https://github.com/LibreCAD/LibreCAD/assets/22447924/0262d89a-fbc0-4ba2-8f73-2f174fe35d2f)
![screen-2023-07-14-20-25-13](https://github.com/LibreCAD/LibreCAD/assets/22447924/716131b8-0b65-4a55-a44b-0bc88fc95f01)
![screen-2023-07-14-20-53-57](https://github.com/LibreCAD/LibreCAD/assets/22447924/41d8c7a8-7683-47bb-af0e-f6f964fab5cd)

### Steps to reproduce or sample file

1. Create drawing with different entities;
2. Apply same style on all entities;
3. Repeat for all line types.

### Operating System and LibreCAD version info

```
Version: 2.2.1_alpha-231-g3974b220
Compiler: GNU GCC 11.3.0
Compiled on: Jul 14 2023
Qt Version: 5.15.3
Boost Version: 1.74.0
System: Debian GNU/Linux 12 (bookworm)
```

### Related issues

- https://github.com/LibreCAD/LibreCAD/issues/1476

**Comment by dxli** [comment] 2023-07-14 19:00
Considered the same issue as #1607 

Need to review all draw methods of basic geometries (line, arc/circle, ellipses, splines(quadratic and cubic)).

Line patterns should be defined in paper space. Current Qt painter supports lines/arcs/circles/complete ellipses, but not elliptic arcs or splines(Confirmation needed).

Another thought: port painter from LibreCAD-v3?

Help needed here.

**Comment by app4soft** [comment] 2023-07-14 19:44
> Considered the same issue as`#1607`

Not directly related to any of this:

1. Circles has different dash/dot/space sizes (smaller) then all other entities;
2. Ellipses has a bit broken look with all line types;
3. Splines with "No Pen" shown as "Continuous";
4. "Dash Dot" and "Dash Dot (small)" has a bit off-centered middle dots (an all objects, except Circle).

**Comment by dxli** [comment] 2023-07-16 12:06
Duplicate of #778

**Comment by app4soft** [comment] 2023-07-22 14:08
Update after 871768d

1. ~~Circles has different dash/dot/space sizes (smaller) then all other entities;~~ Fixed.
2. ~~Ellipses has a bit broken look with all line types;~~ Fixed.
3. Splines with "No Pen" shown as "Continuous" — LibreCAD crashes now, see 1662
4. ~~"Dash Dot" and "Dash Dot (small)" has a bit off-centered middle dots (an all objects, except Circle).~~ Fixed
5. For lines with non-zero line width Line patterns should be defined in paper space.
6. For lines with "`0.00mm`" width Line pattern should be defined in screen space (for printing it should be recalculated to paper space).
7. In "Draft mode" all lines Line patterns should be defined in screen space.

**Comment by dxli** [comment] 2023-07-23 12:55
paperscale support is still broken.

**Comment by app4soft** [comment] 2023-08-01 23:23
One more Line type issue - now on ***"Spline"*** entities: it has problems with any other then `Continuous` Line types (including with selection `Dash (tiny)` Line type).

Also, *"Spline"* looks like there are Line types applied two times same time on top of each other, but with opposite directions.

- DXF file: [seletcion-dash-tiny.zip](https://github.com/LibreCAD/LibreCAD/files/12234602/seletcion-dash-tiny.zip)

![Screenshot_2023-08-02_02-13-31](https://github.com/LibreCAD/LibreCAD/assets/22447924/db50dfbf-e4a8-4d52-97ce-ba5b5de6347d)
![Screenshot_2023-08-02_02-14-33](https://github.com/LibreCAD/LibreCAD/assets/22447924/03116aea-4f7d-4e63-8189-4ebf38e4b02e)
![Screenshot_2023-08-02_02-15-31](https://github.com/LibreCAD/LibreCAD/assets/22447924/d5e50397-9104-491b-b306-44724c6ca7bb)

**Comment by app4soft** [comment] 2023-08-03 23:41
Another issue discovered: Line type's patterns mapped on `Polyline` and `Freehand` per segment, instead of continuous all along from first point to last point.

In same time, it mapped correctly on `Spline`, `Line` and `Spline through points` (i.e. continuously from first point to last point).

![Screenshot_2023-08-04_02-39-27](https://github.com/LibreCAD/LibreCAD/assets/22447924/b08f8edc-7ccd-42cd-b9de-82a08fabf87d)

**Comment by dxli** [comment] 2023-09-21 02:21
drawing a reversed arc is now slower because of commit a6ab92b : the reason: QPainter or QPainterPath doesn't support reversed arcs well, so reversed arcs are now simulated by line segments.

**Closed** 2024-05-16 22:04 UTC
