### ISSUE TITLE
accurate construction line preview

### ISSUE THREAD

**Issue by r-a-v-a-s** [LibreCAD/LibreCAD#787] opened 2016-07-05 05:58 UTC
It would be useful if a construction line's preview was also an 'infinite' line,
as opposed to only a line segment.

I might also make a class for construction lines,
which would optimize drawing.

**Comment by r-a-v-a-s** [comment] 2016-09-10 19:11
I've done so for the '2 points' line tool,
but I've noticed that other tools use RS_Creation....

```c++
void RS_ActionDrawLineParallelThrough::mouseMoveEvent(QMouseEvent* e) {
    RS_DEBUG->print("RS_ActionDrawLineParallelThrough::mouseMoveEvent begin");


    switch (getStatus()) {
    case SetEntity: {
            entity = catchEntity(e, RS2::ResolveAll);
            /*deletePreview();

			RS_Creation creation(preview, nullptr, false);
			creation.createParallelThrough(*coord,
                                           number,
                                           entity);

            drawPreview();*/
        }
        break;

    case SetPos: {
			*coord = snapPoint(e);
            //RS_Vector(graphicView->toGraphX(e->x()),
            //                  graphicView->toGraphY(e->y()));
            deletePreview();

			RS_Creation creation(preview.get(), nullptr, false);
			creation.createParallelThrough(*coord,
                                           number,
                                           entity);

            drawPreview();
        }
        break;

    default:
        break;
    }

    RS_DEBUG->print("RS_ActionDrawLineParallelThrough::mouseMoveEvent end");
}
```

Any ideas on making things more consistent?
Anyone interested in working on this?

**Comment by fa201** [comment] 2023-08-08 22:49
With construction lines, all lines including the circle are not visible.

![construction_lines](https://github.com/LibreCAD/LibreCAD/assets/49532187/e20a678b-3c3b-47a4-896b-637089771b7e)

When I switch off the construction line, it is OK.
![segments](https://github.com/LibreCAD/LibreCAD/assets/49532187/9106d720-164a-49b6-9e4d-13d4c36c1bb2)

Version: 2.2.0.2
Compiler: GNU GCC 9.4.0
Compiled on: Jul 29 2023
Qt Version: 5.12.9
Boost Version: 1.75.0
System: Ubuntu 20.04.6 LTS

**Comment by lordofbikes** [comment] 2023-08-09 08:47
@fa201 I just checked Windows 2.2.0.2 and AppImage on Kunbuntu 22.04, both work as expected.
You use the AppImage on Ubuntu 20.04?

OK, confused now, I found #1676. There 2.2.0.2 shows the expected behavior and the issue is addressed to latest `master` branch.

Anyhow, as the issue already has its own place, I close this because it's implemented already.

**Closed by lordofbikes** 2023-08-09 08:47 UTC
Labels: feature request
