### ISSUE TITLE
Wrong position of text

### ISSUE THREAD

**Issue by bansan85** [LibreCAD/LibreCAD#1684] opened 2023-08-16 14:37 UTC
Texts are wrongly placed in master.

[plans_2023_07_21.zip](https://github.com/LibreCAD/LibreCAD/files/12360509/plans_2023_07_21.zip)

### Expected behavior

Open enclosed file with

Version: 2.2.0.2
Compiler: GNU GCC 13.1.0
Compiled on: Jul 29 2023
Qt Version: 5.12.11
Boost Version: 1.75.0
System: Windows 10 (10.0)

![image](https://github.com/LibreCAD/LibreCAD/assets/9248729/2cec55ee-3866-41b0-8a9e-220e630355d5)

### Observed behavior

Open enclosed file with

Version: 2.2.1_alpha-278-g5064b9ca
Compiler: GNU GCC 13.2.0
Compiled on: Aug 16 2023
Qt Version: 5.15.2
Boost Version: 1.75.0
System: Windows 10 Version 2009

![image](https://github.com/LibreCAD/LibreCAD/assets/9248729/3829163a-8a37-4fbb-b72c-81f19edfa14e)

PS : My windows system is Windows 11 version 22H2 not "Windows 10 Version 2009" (which is probably the one from Github CI).

**Comment by dxli** [comment] 2023-08-16 14:55
It's most likely a regression due to right-to-left text support: PR #1674 

Probably a duplicate of Issue #1675

**Comment by dxli** [comment] 2023-10-20 07:45
Thanks for reporting. The regression was indeed a tricky one passed my code review.

**Closed by dxli** 2023-10-20 07:45 UTC

**Comment by bansan85** [comment] 2023-10-20 09:21
Thanks, I just tested and every thing looks fine. Silly virtual function ;-)
