### ISSUE TITLE
Official release 2.2.0 and Candidate 4 appimage won't open.

### ISSUE THREAD

**Issue by joezhouchenye** [LibreCAD/LibreCAD#1596] opened 2023-03-08 03:46 UTC
Release 2.2.0 Candidate 3 appimage version works well.

### Expected behavior

Official release 2.2.0 appimage version should work.

### Observed behavior

Run once, using AppImageLaunch in terminal

![image](https://user-images.githubusercontent.com/59191277/223613991-f1333f42-700a-4631-8245-580b0e55d2b3.png)

However, 2.2.0 Candidate 3 works fine.

### Operating System and LibreCAD version info

Ubuntu 22.04
LibreCAD 2.2.0

**Comment by lordofbikes** [comment] 2023-03-08 06:59
duplicate of #1594
many thanks for reporting

**Closed** 2023-03-08 06:59 UTC
