### ISSUE TITLE
Commit number in revision info

### ISSUE THREAD

**Issue by kromanenko** [LibreCAD/LibreCAD#495] opened 2015-01-30 16:31 UTC
First i pulled latest code from master. 
Head commit was 
```
commit b5075508fdff1282249c55be6857fe633789aba4
Author: Dongxu Li <dongxuli2011@gmail.com>
Date:   Wed Jan 28 23:04:52 2015 -0500
```
Then i have compiled LibreCAD and viewed version on Help -> About
I see there SCM Revision: 2.0.7-34-**gb6b97ea**.

I found one of previous commits: b6b97ea, but it`s name matches not exactly.

Screenshot attached.
![head commit](https://cloud.githubusercontent.com/assets/10499375/5979097/4e36cdda-a8ad-11e4-87aa-ccd6f2228b6d.PNG)

**Comment by dxli** [comment] 2015-05-30 10:37
the commit number is auto from:
git describe --tags

**Comment by lordofbikes** [comment] 2015-05-30 11:33
This is a duplicate of #494, closing it

**Closed by lordofbikes** 2015-05-30 11:33 UTC
