### ISSUE TITLE
Cant see properties popup box (Kubuntu 18.04)

### ISSUE THREAD

**Issue by JoinJoin** [LibreCAD/LibreCAD#1008] opened 2018-08-14 08:22 UTC
### Expected behavior
Show object properties popup box 

### Observed behavior

No box 

### Steps to reproduce or sample file

Draw a line, select a line, click properties, nothing happens. No popup box. 

### Operating System and LibreCAD version info

Version: 2.1.2
Compiler: GNU GCC 6.2.0
Compiled on: Sep 17 2016
Qt Version: 5.9.5
Boost Version: 1.62.0
System: Ubuntu 18.04.1 LTS

**Comment by lordofbikes** [comment] 2018-08-14 11:47
This is the intended design of this tool.
The properties tool works only with exact one entity. 
So the work flow was designed to first select the tool, then the entity.
The mouse pointer changes the shape to signal that the tool is active.
Then click on any entity, selected or not, to modify its properties.
After closing the properties box, you can direct click the next entity for its properties.

The expected behavior works with the attributes tool, because it can handle multiple selected entities.
When one or more entities are selected, the attributes box opens directly.
If not, multiple entities could be selected, then push ENTER to open the attributes box.

**Closed** 2018-10-11 07:52 UTC
