### ISSUE TITLE
Colors on icons in the toolbar very hard to see

### ISSUE THREAD

**Issue by bit4man** [LibreCAD/LibreCAD#1802] opened 2024-06-06 19:01 UTC
This is vanilla launch of LibreCad (screendump)

![Screenshot from 2024-06-06 14-57-35](https://github.com/LibreCAD/LibreCAD/assets/1713562/0b36ba3e-95b2-4bf7-8fc0-fbb5cdbc6c14)

Perhaps it's due to me being color blind, but it's extremely hard for me to see what these icons do. 

### Expected behavior
Light on dark background cons. Or dark on white icons.  Not very dark on "almost not so dark" icons.

### Observed behavior
See screendump.

### Steps to reproduce or sample file
I've looked but been unable to find a place to adjust the icon colors.

### Operating System and LibreCAD version info
Version: 2.2.0.2
Compiler: GNU GCC 14.0.1
Compiled on: Jan 25 2024
Qt Version: 5.15.14
Boost Version: 1.83.0

**Comment by dxli** [comment] 2024-06-06 20:01
I feel the issue exists in Qt6 builds as well. Highlighting is hard to notice for push buttons.

**Comment by lordofbikes** [comment] 2024-06-06 20:50
closing as duplicate of #1144

**Closed by lordofbikes** 2024-06-06 20:50 UTC
Labels: feature request, duplicate
