### ISSUE TITLE
DWG 2018 (AC1032)

### ISSUE THREAD

**Issue by PABLOCORRO** [LibreCAD/LibreCAD#1274] opened 2020-09-04 04:30 UTC
### Expected behavior
Hi,
Librecad currently cannot open dwg files 2018 (AC1032)

It would be possible for them to implement LIBREDWG currently supports dwg version 2018 (AC1032), I have tried it and it is very good:
https://github.com/LibreDWG/libredwg

Thank's

**Comment by DuncanLithgow** [comment] 2020-12-28 23:54
Duplicate of #1239

**Comment by lordofbikes** [comment] 2020-12-29 00:04
see #1055

**Closed by lordofbikes** 2020-12-29 00:04 UTC
