### ISSUE TITLE
Incorrect import of DXF file with large Hatch

### ISSUE THREAD

**Issue by johnthagen** [LibreCAD/LibreCAD#1353] opened 2021-06-01 19:26 UTC
### Expected behavior

The following AutoCAD DXF 2013 file: [dxf-2013-hatch.dxf](https://github.com/LibreCAD/LibreCAD/files/6580099/dxf-2013-hatch.dxf.txt)

Renders correctly within eDrawings Viewer 29.2.0.0029 on macOS 10.15.7:

<img width="1579" alt="Screen Shot 2021-06-01 at 3 15 27 PM" src="https://user-images.githubusercontent.com/10340167/120378299-3d36bd00-c2ec-11eb-9a1f-dd3a05a12481.png">

And also in Autodesk DWG TrueView 2022 on Windows 10:

<img width="1527" alt="Screen Shot 2021-06-01 at 3 23 50 PM" src="https://user-images.githubusercontent.com/10340167/120379220-715ead80-c2ed-11eb-8459-d38142c085ef.png">

But in LibreCAD 2.2.0-rc2 on macOS 10.15.7:

There are significant rendering artifacts:

<img width="2028" alt="Screen Shot 2021-06-01 at 3 25 39 PM" src="https://user-images.githubusercontent.com/10340167/120379372-a9fe8700-c2ed-11eb-9e9b-cd2ece21f7f2.png">

### Operating System and LibreCAD version info

```
Version: 2.2.0-rc2
Compiler: Clang 10.0.0
Compiled on: Dec 31 2020
Qt Version: 5.14.2
Boost Version: 1.71.0
System: macOS 10.15
```

**Comment by pollywinters** [comment] 2022-04-06 20:54
Applying PR #1354, I find that there is an error produced in file librecad/src/src.pro
The line `lib/gui/rs_linetypepattern.cpp \` becomes duplicated, resulting in build failure.
Removing the duplicate of the line allows the build to complete. The sample DXF file provided by https://github.com/johnthagen will then open and display correctly.
Note added to PR #1354

**Closed** 2022-04-16 11:33 UTC
