### ISSUE TITLE
program freezes on print preview

### ISSUE THREAD

**Issue by FRKgh** [LibreCAD/LibreCAD#722] opened 2016-05-18 18:49 UTC
PPAs:
deb http://ppa.launchpad.net/librecad-dev/librecad-daily/ubuntu trusty main
deb-src http://ppa.launchpad.net/librecad-dev/librecad-daily/ubuntu trusty main

Latest download:
Version: 2.1.0-beta
SCM Revision: 2.1.0
Compiler: GNU GCC 4.8.4
Compiled on: May 18 2016
Qt Version: 5.2.1
Boost Version: 1.54.0

Start LibreCAD with default blank document
**Print Preview** on blank document
LibreCAD freezes. Have to **Force Quit**

OS: LinuxMint 17.3 Rosa

Is there something wrong at my end? I have had a completely malfunctioning revision before; fortunately, it got fixed with subsequent daily updates.

How does one roll-back to a previous revision?

Thank you.

**Comment by r-a-v-a-s** [comment] 2016-05-18 19:46
Make two issues; and have their titles be the most concise description of the issue (e.g. "program freezes on print preview").

I can't reproduce issue 1.
I can reproduce issue 2.

**Comment by r-a-v-a-s** [comment] 2016-05-18 19:55
I simplified this issue so you can just make one more for the other.

It looks like the program is getting stuck in a loop... debug:
```
RS_ActionInterface::RS_ActionInterface: Setting up action: "Print Preview"
RS_ActionInterface::RS_ActionInterface: Setting up action: "Print Preview": OK
QG_DialogFactory::requestOptions
QG_DialogFactory::requestOptions: OK
  adding listeners
  showing MDI window
RS_VariableDict::addVariable()
```
Then it just continuously produces `RS_VariableDict::addVariable()`

**Comment by lordofbikes** [comment] 2016-05-18 20:09
The removed issue 1 could be a duplicate of #711, maybe @FRKgh can check this.

**Comment by r-a-v-a-s** [comment] 2016-05-18 23:47
It was a recursive error.
I don't know what changed to cause this,
nor do I fully understand the section of code;
however, the change does avoid the freezing.

Hopefully someone can review this.

**Comment by FRKgh** [comment] 2016-05-19 15:31
Version: 2.1.0-beta
Compiler: GNU GCC 4.8.4
Compiled on: May 19 2016
Qt Version: 5.2.1
Boost Version: 1.54.0

Freezing resolved.

**Print Preview** and **Auto Zoom** resolved, BUT, only for drawings created in this build.

**Print Preview** and **Auto Zoom** still do not work for drawings that used to work in builds two revisions ago.

**Closed** 2016-05-19 15:32 UTC
Labels: bug
