### ISSUE TITLE
Direct Distance Entry

### ISSUE THREAD

**Issue by grandixximo** [LibreCAD/LibreCAD#1741] opened 2024-02-20 06:11 UTC
Requesting this feature which may simplify certain drawing aspects.

Direct distance entry is a feature that allows users to draw objects at specific distances by using the cursor to point in the desired direction and inputting the distance at the command line. To use this feature effectively, one might start by initiating the Line command and specifying a starting point. By enabling Polar Tracking, the user can ensure that the line is constrained to specific angles, such as horizontal or vertical directions. As the cursor is moved in the intended direction, entering the desired length (e.g., 30 units) and pressing Return will create a line of that length in the direction pointed to. This method can be adjusted for various angles by configuring Polar Tracking or using Ortho for strictly horizontal or vertical lines. The feature also provides dynamic feedback through Tool Tips, showing the relative polar coordinate from the start point to the cursor's current position, aiding in precision drawing. This capability is particularly useful for creating drawings quickly and accurately without the need for excessive manual input or adjustments.

I also see it mentioned in the User Manual for version 2.1.3 but it does not seem to work.
https://wiki.librecad.org/images/2/20/LibreCAD_Users_Manual_2.1.3.pdf

Some nice fellow also posted a sample implementation

https://forum.librecad.org/Direct-Distance-Entry-td5714732.html

[DirectDistanceEntry.zip](https://github.com/LibreCAD/LibreCAD/files/14340140/DirectDistanceEntry.zip)

Would be great to have, for polyline and move.

**Comment by lordofbikes** [comment] 2024-02-20 20:01
duplicate of #1210

**Closed by lordofbikes** 2024-02-20 20:01 UTC
Labels: duplicate
