### ISSUE TITLE
Crash during reading LFF fonts

### ISSUE THREAD

**Issue by sand1024** [LibreCAD/LibreCAD#1784] opened 2024-05-13 14:50 UTC
Hi! 
It seems that version built from master using QT6 (64-bit) crashes on reading .lff font.

Crash is due to the following assert:
ASSERT: "rc <= 0xffff" in file D:/Qt/QT6/6.7.0/mingw_64/include/QtCore/qchar.h, line 79

It occurs in rs_font.cpp:342

Sample file attached

**Comment by dxli** [comment] 2024-05-13 22:51
Can you upload the sample lff ?

**Comment by sand1024** [comment] 2024-05-14 07:48
the font is amiri-regular.llf (standard one)
If I'm correct, based on debugger the assert occurs on line [#1EE00] - line number 7204

**Comment by dxli** [comment] 2024-05-14 09:44
Again, this is a real issue with lff font implementation:

QChar is for utf-16, so the range is 16bit, and we cannot pass any value beyond 16 but while using the int type.

Looks like we have to use the string::fromutf8() instead

**Comment by lordofbikes** [comment] 2024-05-14 10:31
Where is this LFF file from?
I checked branches, but I couldn't find a `amiri-regular.llf` with code `[#1EE00]`.
All I found ended in line 7203, at code `[FEFC]`.

I've checked all fonts for correctness a while ago and there was nothing added to fonts to my knowledge.

LFF format is limited to utf-16 yet and we could not accept contributions that exceed this limit.
Anyhow, of course LibreCAD should not crash with malicious LFF files.
This needs limit checks in [rs_filterlff.cpp](https://github.com/LibreCAD/LibreCAD/blob/master/librecad/src/lib/filters/rs_filterlff.cpp) where the code is used without further proving.

**Comment by sand1024** [comment] 2024-05-14 11:01
well, it's a good question... I suppose I've picked it from fonts that are part of 2.2.0 - yet probably its old install, the date of font file on my machine is Dec 17, 2022 which is the same as build date

Version 
Version: 2.2.0
Compiler: GNU GCC 12.2.0
Compiled on: Dec 17 2022
Qt Version: 5.12.11
Boost Version: 1.75.0
System: Windows 10 (10.0)

**Comment by dongxuli-concord-design** [comment] 2024-05-14 11:30
We can remove the limit of 16 bit now, since utf is supposed to be universal.

**Comment by dxli** [comment] 2024-05-14 13:57
@lordofbikes 

1, the file format itself if compatible with unicode beyond 16bit;
2, step by step, LibreCAD side can remove the 16bit limitation;
3, also need to fix ttf2lff. I assume it has the same limitation. 

I am a little busy now. Wondering @sand1024 would like to help here. 

I  suggest we also back port the fix to 2.2.1 and 2.2.0, where no assertion is raised, potentially even more confusing to end users

**Comment by lordofbikes** [comment] 2024-05-14 14:58
I found these font issues by accident. It is no issue using the fonts for text entities, but opening them to modify letters graphically raised the issue.
As it was not reported before June 2023, I assume, that opening font files is a rarely used feature of LibreCAD. I suspect most font contributions were created with a text editor, copying and modifying existing letters. This also explains the existence of the malicious font files.

So we can't change or fix existing installations, and with the above said, I see no need, even if it was possible.
It is fixed in `2.2.0` with b6b7860805c4aea323ddabde27f8830be694eaa6 and thus fixed in our official stable release `2.2.0.2`.
It was fixed in `master` with 82e2c3e9ef596ff0f82c2a057bdc3498dd4bf9b5 and thus fixed in `2.2.1` already and of course `2.2.2_alpha` too.

Thus no need for urgent actions currently.

**Comment by lordofbikes** [comment] 2024-05-14 15:24
Remembering #1687 I suggest some investigation before putting any efforts into this.
I think there is still a big mess out there, concerning OS platforms and their support for localized letter support. Issue #1687 is about discrepancies between input methods and local letter encoding.
There is Unicode, Codepage system and various UTF formats spread about our supported platforms.
So I'm not sure yet, if just supporting 32-bit letter codes solves any problems.
This might need some investigation in advance, e.g. about current unicode standard, truetype format or OS support for localization, to see if and how it can be useful at all.
Just to be sure not to open Pandora's box, with feeding 32-bit letter codes into our Text entities.

**Comment by dongxuli-concord-design** [comment] 2024-05-14 15:54
I feel it's a step by step process to remove artificial limitations due to our own implementation. 

The current Unicode standard 15.1(2023) contains 149,813 characters. 

16 bit is not even enough to have proper Chinese support, for example. 

We don't handle locales graceful, but limiting it to 16 bit would leave some users no easy alternative within one locale setting.

The issue is probably limited to Chinese. Japanese only uses a subset of Chinese characters, so should be okay with 16bit limitation. I am not aware of any other languages extensively based on characters(instead of alphabet).

**Comment by dxli** [comment] 2024-05-16 15:44
fixed in rs_font

need to check implementation in ttf2lff

**Comment by dxli** [comment] 2024-05-16 21:56
tff2lff is already using uint32 for char code, so it doesn't have the limitation of 16 bit char code.

Closing this issue.

**Closed by dxli** 2024-05-16 21:56 UTC
Labels: feature request, rework
