### ISSUE TITLE
[Feature request] perpendicular/normal snap

### ISSUE THREAD

**Issue by Combinacijus** [LibreCAD/LibreCAD#1265] opened 2020-07-20 18:32 UTC
Now when I draw second line there's no snap when lines are perpendicular
![image](https://user-images.githubusercontent.com/16375702/87970485-7eefb800-cacc-11ea-9234-f23384e19014.png)

It would be nice if those lines snapped when perpendicular
![image](https://user-images.githubusercontent.com/16375702/87970575-a050a400-cacc-11ea-81c0-78f377d88a2a.png)

In general would be nice to have ability to draw perpendicular/normal lines form any shape like lines, circles or even splines. Coming from AutoCAD I really miss this feature. One of the use cases is to make 3-point rectangles aka rotated rectangles which is not a feature either.

**Comment by lordofbikes** [comment] 2020-07-21 17:08
I close this as duplicate of #731, which is now cross linked with this request.
See my post there for a work around with orthogonal line tool. This will do what you need, not at the AutoCAD speed, but the result will be the same.
If you have any comments not mentioned in #731, feel free to add it there.

**Closed by lordofbikes** 2020-07-21 17:08 UTC
