### ISSUE TITLE
Windows installer installs for all users but creates shortcut for only the user who installed LibreCAD

### ISSUE THREAD

**Issue by alx9r** [LibreCAD/LibreCAD#783] opened 2016-06-26 17:57 UTC
Suppose there are two users of a Windows computer, `un1` and `un2`.  Suppose that `un1` installs LibreCAD.  The LibreCAD installer creates a shortcut at `C:\Users\un1\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\LibreCAD`.  That shortcut appears on `un1`'s start menu.  `un2`'s start menu, on the other hand, does not show the shortcut.  `un2` is able to run LibreCAD by running `LibreCAD.exe` directly, but the shortcut is missing from the start menu.

It is customary for programs that are installed for all users on windows to create a shortcut at `C:\ProgramData\Microsoft\Windows\Start Menu` instead.  Those shortcuts are available to all users.

It looks like [createShortCut uses constant `$SMPrograms`](https://github.com/LibreCAD/LibreCAD/blob/709e43ac07cbcced7096a3d0104d141a5b599424/scripts/postprocess-windows/nsis.txt#L102-L108).  `$SMPrograms` is an [NSIS constant](http://nsis.sourceforge.net/Docs/Chapter4.html#varconstant) that depends on the parameter passed to [`SetShellVarContext`](http://nsis.sourceforge.net/Docs/Chapter4.html#setshellvarcontext).  It doesn't look like there is a call to `SetShellVarContext`.  

For what it's worth, [here are the NSIS instructions that creates the shortcuts for another project using NSIS installer](https://github.com/OpenCPN/OpenCPN/blob/b34ba3fc798a39521ca7eec2e6d29f8ac721254a/NSIS.template.in#L777-L797).  That installer calls `SetShellVarContext all` and indeed creates the shortcuts in `C:\ProgramData\Microsoft\Windows\Start Menu`.

This isn't a huge deal for standalone users since a user can manually create their own shortcuts after-the-fact.  It does, however, complicate unattended installation in larger organizations because those installations are often performed as a different user from the person who would actually be using LibreCAD.  Without manual intervention after such an unattended installation, users can't discover LibreCAD from their start menu.

**Comment by lordofbikes** [comment] 2016-06-26 19:13
duplicate of #695

**Closed by lordofbikes** 2016-06-26 19:13 UTC
